name: Build release zip

on:
  push:
#    # Pattern matched against refs/tags
#    tags:
#      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build theme
        run: |
          npm install
          npm run build
          npm run scss-build
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          php wp-cli.phar package install wp-cli/dist-archive-command
          php wp-cli.phar  dist-archive . ./scout-wordpress-theme.zip --plugin-dirname=scout-wordpress-theme
      - uses: actions/upload-artifact@v3
        with:
          name: scout-wordpress-theme.zip
          path: scout-wordpress-theme.zip

#      - name: FTP Deploy to WP Engine (Production)
#        uses: SamKirkland/FTP-Deploy-Action@4.0.0
#        with:
#          server: 1stgossomsendscouts.org.uk
#          username: github@1stgossomsendscouts.org.uk
#          password: ${{ secrets.FTP_PASSWORD }}
#          local-dir: ./
#          server-dir: wp.1stgossomsendscouts.org.uk/public_html/wp-content/themes/scout-wordpress-theme