name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Set version number
        run: |
          old_str="\"version\": \"0.0.0\""
          new_str="\"version\": \"$RELEASE_VERSION\""
          sed -i "s/$old_str/$new_str/g" package.json
          old_str="Version: 0.0.0"
          new_str="Version: ${RELEASE_VERSION:1}"
          sed -i "s/$old_str/$new_str/g" style.css
          git config user.email "github@1stgossomsendscouts.org.uk"
          git config user.name "Github Actions"
          npm install
          git add package.json style.css package-lock.json
          git commit -m "Update version numbers to $RELEASE_VERSION"
          git tag -f ${GITHUB_REF#refs/*/}
          git push -f --tags
      - name: Build theme
        run: |
          npm install
          npm run build
          npm run build-blocks
          npm run scss-build
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          php wp-cli.phar package install wp-cli/dist-archive-command
          php wp-cli.phar  dist-archive . ./scout-wordpress-theme.zip --plugin-dirname=scout-wordpress-theme
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: scout-wordpress-theme.zip
          generate_release_notes: true
          draft: true

