name: Deploy theme to demo site

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: demo
    concurrency: demo
    steps:
    - name: Split branch name
      env:
        GITHUB_REF: ${{ github.ref }}
      id: split
      run: echo "::set-output name=version::${GITHUB_REF##*/}"
    - name: Install theme on demo server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
#        fingerprint: ${{ secrets.SSH_FINGERPRINT }} not working
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.SERVER_WP_PATH }}
          wp theme install ${{ github.server_url }}/${{ github.repository }}/releases/download/${{ steps.split.outputs.version }}/scout-wordpress-theme.zip --force