name: Run build

on:
  pull_request:

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Use Node.js 22
        uses: actions/setup-node@v2
        with:
          node-version: 22
      - name: Build theme
        run: |
          npm install
          npm run build
          npm run build-blocks
          npm run scss-build
